
name: ai_companion
description: A Flutter package for a personal AI companion providing psychological support.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_local_notifications: ^8.0.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
